name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: echo ${DOCKER_PASSWORD} | docker login $docker.pkg.github.com -u ${DOCKER_USERNAME} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build . -t docker.pkg.github.com/ldiqual/docker-msvc/docker:latest
    - run: docker push docker.pkg.github.com/ldiqual/docker-msvc/docker:latest
    