name: Docker Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ldiqual --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - run: docker build . -t ldiqual/docker-msvc
    